version: "2.1"
services:
  jenkins:
    image: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADMIN_INITIAL_PASSWORD=password
volumes:
  jenkins_home:
    driver: local